import {
	access,
	mkdir,
	mkdtemp,
	readFile,
	symlink,
	writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import {
	executeDependencyBootstrap,
	prepareDependencyBootstrap,
} from "./dependency-bootstrap.js";
import { CloneUnsupportedError } from "./dir-clone.js";

function createFailureStore() {
	const failures = new Set<string>();
	return {
		isCached: async (repoRoot: string, directory: string) =>
			failures.has(`${repoRoot}:${directory}`),
		cache: async (repoRoot: string, directory: string) => {
			failures.add(`${repoRoot}:${directory}`);
		},
		clear: async (repoRoot: string, directory: string) => {
			failures.delete(`${repoRoot}:${directory}`);
		},
	};
}

function createReporter() {
	const events: string[] = [];
	return {
		emitCachedFailureWarnings: true,
		measureCloneSize: false,
		write: () => undefined,
		cloned: () => undefined,
		dependency: (event: { state: string; message: string }) => {
			events.push(`${event.state}:${event.message}`);
		},
		events,
	};
}

async function prepareNodePlan(
	mode: "cow-then-repair" | "install-only",
): Promise<{
	repoRoot: string;
	worktreePath: string;
	plan: Awaited<ReturnType<typeof prepareDependencyBootstrap>>;
}> {
	const repoRoot = await mkdtemp(join(tmpdir(), "gji-bootstrap-repo-"));
	const worktreePath = await mkdtemp(join(tmpdir(), "gji-bootstrap-worktree-"));
	await writeFile(join(repoRoot, "pnpm-lock.yaml"), "lockfileVersion: '9'\n");
	await mkdir(join(repoRoot, "node_modules"));

	const plan = await prepareDependencyBootstrap(mode, {
		repoRoot,
		runCommand: async () => undefined,
		stderr: () => undefined,
		worktreePath,
	});
	return { repoRoot, worktreePath, plan };
}

describe("dependencyBootstrap adapters", () => {
	it("seeds node_modules with CoW and always runs the frozen pnpm repair", async () => {
		// Given a pnpm source with a reusable dependency tree and a fresh worktree.
		const { repoRoot, worktreePath, plan } =
			await prepareNodePlan("cow-then-repair");
		const reporter = createReporter();
		const commands: string[] = [];

		// When dependency bootstrap executes with an injected CoW clone and repair runner.
		const result = await executeDependencyBootstrap(plan, {
			cloneDirectory: async (_source, destination) => {
				await mkdir(destination, { recursive: true });
				await writeFile(join(destination, ".modules.yaml"), "stale\n");
				return { bytes: 1, ms: 1 };
			},
			failureStore: createFailureStore(),
			repoRoot,
			reporter,
			runCommand: async (command, cwd) => {
				commands.push(command);
				await expect(
					readFile(join(cwd, "node_modules", ".modules.yaml"), "utf8"),
				).rejects.toThrow();
				await mkdir(join(cwd, "node_modules"), { recursive: true });
				await writeFile(
					join(cwd, "node_modules", ".modules.yaml"),
					"regenerated\n",
				);
			},
		});

		// Then cloning is a seed only, pnpm repair runs, and metadata is regenerated by the repair.
		expect(result.ready).toBe(true);
		expect(commands).toEqual(["pnpm install --frozen-lockfile"]);
		expect(result.events.map(({ state }) => state)).toEqual([
			"seeded",
			"repaired",
		]);
		await expect(
			readFile(join(worktreePath, "node_modules", ".modules.yaml"), "utf8"),
		).resolves.toBe("regenerated\n");
	});

	it("uses npm install-only and never attempts a CoW seed", async () => {
		// Given an npm lockfile and no dependency target in a new worktree.
		const repoRoot = await mkdtemp(join(tmpdir(), "gji-bootstrap-npm-repo-"));
		const worktreePath = await mkdtemp(
			join(tmpdir(), "gji-bootstrap-npm-worktree-"),
		);
		await writeFile(join(repoRoot, "package-lock.json"), "{}\n");
		const plan = await prepareDependencyBootstrap("cow-then-repair", {
			repoRoot,
			runCommand: async () => undefined,
			stderr: () => undefined,
			worktreePath,
		});
		const reporter = createReporter();
		let cloneCalled = false;
		const commands: string[] = [];

		// When dependency bootstrap executes for npm.
		const result = await executeDependencyBootstrap(plan, {
			cloneDirectory: async () => {
				cloneCalled = true;
				return { ms: 1 };
			},
			failureStore: createFailureStore(),
			repoRoot,
			reporter,
			runCommand: async (command) => {
				commands.push(command);
			},
		});

		// Then npm runs destructive install-only repair and no clone is attempted.
		expect(result.ready).toBe(true);
		expect(cloneCalled).toBe(false);
		expect(commands).toEqual(["npm ci"]);
		expect(result.events.at(-1)?.state).toBe("installed");
	});

	it("falls back to a clean repair when CoW is unsupported and caches the failure", async () => {
		// Given a pnpm source whose filesystem rejects CoW.
		const { repoRoot, worktreePath, plan } =
			await prepareNodePlan("cow-then-repair");
		const reporter = createReporter();
		const failureStore = createFailureStore();
		let cloneCalled = false;
		let repairCalled = false;

		// When the clone fails with an explicit unsupported-filesystem error.
		const result = await executeDependencyBootstrap(plan, {
			cloneDirectory: async () => {
				cloneCalled = true;
				throw new CloneUnsupportedError("reflinks unavailable");
			},
			failureStore,
			repoRoot,
			reporter,
			runCommand: async () => {
				repairCalled = true;
			},
		});

		// Then ordinary copy is never attempted, while repair still makes progress and the failure is cached.
		expect(result.ready).toBe(true);
		expect(cloneCalled).toBe(true);
		expect(repairCalled).toBe(true);
		expect(result.events.map(({ state }) => state)).toEqual([
			"fallback",
			"repaired",
		]);
		expect(await failureStore.isCached(repoRoot, "node_modules")).toBe(true);
		void worktreePath;
	});

	it("removes a failed seed before retrying clean and preserves no partial clone", async () => {
		// Given a source whose first repair fails after a successful seed.
		const { repoRoot, worktreePath, plan } =
			await prepareNodePlan("cow-then-repair");
		const reporter = createReporter();
		let repairAttempts = 0;
		let targetExistedOnRetry = true;

		// When the first repair fails and the clean retry is allowed to run.
		const result = await executeDependencyBootstrap(plan, {
			cloneDirectory: async (_source, destination) => {
				await mkdir(destination, { recursive: true });
				await writeFile(join(destination, "partial.txt"), "partial\n");
				return { ms: 1 };
			},
			failureStore: createFailureStore(),
			repoRoot,
			reporter,
			runCommand: async (_command, cwd) => {
				repairAttempts += 1;
				if (repairAttempts === 1) throw new Error("stale seed");
				targetExistedOnRetry = await pathExists(join(cwd, "node_modules"));
				await mkdir(join(cwd, "node_modules"), { recursive: true });
			},
		});

		// Then the retry sees a clean target and leaves a successful repaired worktree.
		expect(result.ready).toBe(true);
		expect(repairAttempts).toBe(2);
		expect(targetExistedOnRetry).toBe(false);
		await expect(
			readFile(join(worktreePath, "node_modules", "partial.txt"), "utf8"),
		).rejects.toThrow();
	});

	it("never deletes a target that existed before the bootstrap command", async () => {
		// Given a pre-existing dependency target with a user-owned sentinel file.
		const repoRoot = await mkdtemp(
			join(tmpdir(), "gji-bootstrap-existing-repo-"),
		);
		const worktreePath = await mkdtemp(
			join(tmpdir(), "gji-bootstrap-existing-worktree-"),
		);
		await writeFile(join(repoRoot, "pnpm-lock.yaml"), "lock\n");
		await mkdir(join(repoRoot, "node_modules"));
		await mkdir(join(worktreePath, "node_modules"));
		await writeFile(join(worktreePath, "node_modules", "keep.txt"), "keep\n");
		const plan = await prepareDependencyBootstrap("cow-then-repair", {
			repoRoot,
			runCommand: async () => undefined,
			stderr: () => undefined,
			worktreePath,
		});
		const reporter = createReporter();

		// When repair fails against the existing target.
		const result = await executeDependencyBootstrap(plan, {
			failureStore: createFailureStore(),
			repoRoot,
			reporter,
			runCommand: async () => {
				throw new Error("repair failed");
			},
		});

		// Then bootstrap reports failure without removing user-owned state.
		expect(result.ready).toBe(false);
		await expect(
			readFile(join(worktreePath, "node_modules", "keep.txt"), "utf8"),
		).resolves.toBe("keep\n");
	});

	it("rejects a symlinked source outside the selected repository root", async () => {
		// Given a lockfile and a node_modules symlink that escapes the repository.
		const repoRoot = await mkdtemp(join(tmpdir(), "gji-bootstrap-link-repo-"));
		const external = await mkdtemp(
			join(tmpdir(), "gji-bootstrap-link-external-"),
		);
		const worktreePath = await mkdtemp(
			join(tmpdir(), "gji-bootstrap-link-worktree-"),
		);
		await writeFile(join(repoRoot, "pnpm-lock.yaml"), "lock\n");
		await mkdir(join(external, "package"));
		await symlink(external, join(repoRoot, "node_modules"));
		const plan = await prepareDependencyBootstrap("cow-then-repair", {
			repoRoot,
			runCommand: async () => undefined,
			stderr: () => undefined,
			worktreePath,
		});
		const reporter = createReporter();
		let cloneCalled = false;

		// When bootstrap evaluates the source.
		const result = await executeDependencyBootstrap(plan, {
			cloneDirectory: async () => {
				cloneCalled = true;
				return { ms: 1 };
			},
			failureStore: createFailureStore(),
			repoRoot,
			reporter,
			runCommand: async () => undefined,
		});

		// Then the unsafe source is skipped without cloning and repair remains the only fallback.
		expect(result.ready).toBe(true);
		expect(cloneCalled).toBe(false);
		expect(result.events[0]?.state).toBe("fallback");
	});

	it("clones a compatible uv environment and repairs it with locked sync", async () => {
		// Given a uv lockfile and a virtual environment with a compatible interpreter fingerprint.
		const repoRoot = await mkdtemp(join(tmpdir(), "gji-bootstrap-uv-repo-"));
		const worktreePath = await mkdtemp(
			join(tmpdir(), "gji-bootstrap-uv-worktree-"),
		);
		await writeFile(join(repoRoot, "uv.lock"), "versioned\n");
		await mkdir(join(repoRoot, ".venv", "bin"), { recursive: true });
		await writeFile(join(repoRoot, ".venv", "pyvenv.cfg"), "version = 3.13\n");
		const plan = await prepareDependencyBootstrap("cow-then-repair", {
			checkUvRuntime: async () => true,
			repoRoot,
			runCommand: async () => undefined,
			stderr: () => undefined,
			worktreePath,
		});
		const commands: string[] = [];

		// When uv bootstrap runs.
		const result = await executeDependencyBootstrap(plan, {
			cloneDirectory: async (_source, destination) => {
				await mkdir(destination, { recursive: true });
				return { ms: 1 };
			},
			failureStore: createFailureStore(),
			repoRoot,
			reporter: createReporter(),
			runCommand: async (command) => {
				commands.push(command);
			},
		});

		// Then uv reuses the environment only after the locked repair succeeds.
		expect(result.ready).toBe(true);
		expect(commands).toEqual(["uv sync --locked"]);
		expect(result.events.map(({ state }) => state)).toEqual([
			"seeded",
			"repaired",
		]);
	});

	it("falls back safely when the Python runtime is incompatible", async () => {
		// Given a uv environment that cannot run under the current interpreter.
		const repoRoot = await mkdtemp(
			join(tmpdir(), "gji-bootstrap-uv-mismatch-repo-"),
		);
		const worktreePath = await mkdtemp(
			join(tmpdir(), "gji-bootstrap-uv-mismatch-worktree-"),
		);
		await writeFile(join(repoRoot, "uv.lock"), "versioned\n");
		await mkdir(join(repoRoot, ".venv"), { recursive: true });
		const plan = await prepareDependencyBootstrap("cow-then-repair", {
			checkUvRuntime: async () => false,
			repoRoot,
			runCommand: async () => undefined,
			stderr: () => undefined,
			worktreePath,
		});
		let cloneCalled = false;

		// When bootstrap evaluates the incompatible seed.
		const result = await executeDependencyBootstrap(plan, {
			cloneDirectory: async () => {
				cloneCalled = true;
				return { ms: 1 };
			},
			failureStore: createFailureStore(),
			repoRoot,
			reporter: createReporter(),
			runCommand: async () => undefined,
		});

		// Then it does not clone an incompatible interpreter environment and repairs from empty state.
		expect(result.ready).toBe(true);
		expect(cloneCalled).toBe(false);
		expect(result.events.map(({ state }) => state)).toEqual([
			"fallback",
			"repaired",
		]);
	});

	it("clones Cargo build state before cargo check repair", async () => {
		// Given a Cargo lockfile and an existing target cache.
		const repoRoot = await mkdtemp(join(tmpdir(), "gji-bootstrap-cargo-repo-"));
		const worktreePath = await mkdtemp(
			join(tmpdir(), "gji-bootstrap-cargo-worktree-"),
		);
		await writeFile(join(repoRoot, "Cargo.lock"), "version = 3\n");
		await mkdir(join(repoRoot, "target", "debug"), { recursive: true });
		const plan = await prepareDependencyBootstrap("cow-then-repair", {
			repoRoot,
			runCommand: async () => undefined,
			stderr: () => undefined,
			worktreePath,
		});
		const commands: string[] = [];

		// When the Cargo adapter bootstraps the worktree.
		const result = await executeDependencyBootstrap(plan, {
			cloneDirectory: async (_source, destination) => {
				await mkdir(destination, { recursive: true });
				return { ms: 1 };
			},
			failureStore: createFailureStore(),
			repoRoot,
			reporter: createReporter(),
			runCommand: async (command) => {
				commands.push(command);
			},
		});

		// Then the build cache is reported as repaired rather than as a dependency install.
		expect(result.ready).toBe(true);
		expect(commands).toEqual(["cargo check"]);
		expect(result.events[0]?.kind).toBe("build-cache");
		expect(result.events.at(-1)?.state).toBe("repaired");
	});
});

async function pathExists(path: string): Promise<boolean> {
	try {
		await access(path);
		return true;
	} catch {
		return false;
	}
}
